# Generated by Django 3.1.3 on 2021-04-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrackerapp', '0002_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
